apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: vote
        app: voting-app
    spec:
      containers:
      - name: worker
        image: jpoon/vote:latest
        env:
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: account-name
        - name: AZURE_STORAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: access-key
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: vote
